name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    lint:
        name: "Linter check"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Install Ruff
              run: pip install ruff
            
            - name: Run Ruff linter
              run: ruff check .
            
            - name: Run Ruff formatter check
              run: ruff format --check .

    deploy:
        name: "Deploy to VPS"
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Configure SSH
              env:
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_IP: ${{ secrets.SSH_IP }}
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
                chmod 600 ~/.ssh/deploy-key.pem
                cat >> ~/.ssh/config <<END
                Host my-vps
                    HostName $SSH_IP
                    User $SSH_USER
                    IdentityFile ~/.ssh/deploy-key.pem
                    StrictHostKeyChecking no
                END
          
            - name: Deploy site
              run: ssh my-vps '~/redeploy-site.sh'

            - name: Notify Discord - Success
              run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful"
            
            - name: Notify Discord - Failure
              if: failure()
              run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed"