name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Tests
        env:
            TESTING: true
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.12
            
            - name: Setup Python Virtual Environment
              run: python -m venv python3-virtualenv && source python3-virtualenv/bin/activate

            - name: Install dependencies
              run: python3-virtualenv/bin/pip install -r requirements.txt
            
            - name: Run Tests
              run: chmod +x run_test.sh && ./run_test.sh

            
            